# Generated by Django 4.2.11 on 2025-04-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_suggestion', '0002_delete_pricingsuggestion'),
        ('demand_forecasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('predicted_quantity', models.FloatField()),
                ('yhat_lower', models.FloatField()),
                ('yhat_upper', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('days_predicted', models.IntegerField()),
                ('current_inventory', models.FloatField()),
                ('inventory_shortfall', models.FloatField()),
                ('inventory_excess', models.FloatField()),
                ('projected_revenue', models.FloatField()),
                ('plot_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.FloatField()),
                ('base_price', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='semanticlabel',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
        migrations.AddField(
            model_name='inventory',
            name='semantic_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand_forecasting.semanticlabel'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand_forecasting.subcategory'),
        ),
        migrations.AddField(
            model_name='forecastresult',
            name='semantic_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand_forecasting.semanticlabel'),
        ),
        migrations.AddField(
            model_name='forecastresult',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand_forecasting.subcategory'),
        ),
    ]
