# Generated by Django 4.2.11 on 2025-04-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand_forecasting', '0002_forecastresult_inventory_alter_semanticlabel_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastresult',
            options={'verbose_name': 'Forecast Result', 'verbose_name_plural': 'Forecast Results'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='semanticlabel',
            options={'verbose_name': 'Semantic Label', 'verbose_name_plural': 'Semantic Labels'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='days_predicted',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='inventory_excess',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='inventory_shortfall',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='projected_revenue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='semantic_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='demand_forecasting.semanticlabel'),
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='demand_forecasting.subcategory'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='base_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='current_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='semantic_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='demand_forecasting.semanticlabel'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='demand_forecasting.subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='forecastresult',
            unique_together={('subcategory', 'semantic_label', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('subcategory', 'semantic_label')},
        ),
    ]
