# Generated by Django 4.2.11 on 2025-04-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_forecasting', '0003_alter_forecastresult_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastresult',
            options={'ordering': ['-date'], 'verbose_name': 'Forecast Result', 'verbose_name_plural': 'Forecast Results'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['subcategory', 'semantic_label'], 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='semanticlabel',
            options={'ordering': ['label'], 'verbose_name': 'Semantic Label', 'verbose_name_plural': 'Semantic Labels'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterUniqueTogether(
            name='forecastresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='forecastresult',
            constraint=models.UniqueConstraint(fields=('subcategory', 'semantic_label', 'date'), name='unique_forecast'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('subcategory', 'semantic_label'), name='unique_inventory'),
        ),
    ]
