# Generated by Django 5.0.2 on 2025-04-26 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demand_forecasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('action', models.CharField(max_length=100)),
                ('forecast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demand_forecasting.forecast')),
            ],
        ),
    ]
