# Generated by Django 4.2.11 on 2025-04-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_suggestion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingSuggestion',
        ),
    ]
