# Generated by Django 5.1.6 on 2025-04-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_suggestion', '0002_delete_pricingsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePredictionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('predicted_sales', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
