# Generated by Django 4.2.11 on 2025-05-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_suggestion', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricepredictionrequest',
            name='suggested_price',
            field=models.FloatField(null=True),
        ),
    ]
